include:
  - _compose.base.app.yaml
  - _compose.base.db.yaml

services:
  traefik:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.local.yaml:/etc/traefik/traefik.yaml:ro
    labels:
      traefik.http.routers.dashboard.entrypoints: web

  frontend:
    labels:
      traefik.http.routers.frontend.entrypoints: web

  backend:
    labels:
      traefik.http.routers.backend.entrypoints: web

  database:
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data: